"""empty message

Revision ID: f7fbc0a5722a
Revises: 
Create Date: 2021-01-05 00:29:36.315828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7fbc0a5722a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('c1_red', sa.Integer(), nullable=True),
    sa.Column('c1_green', sa.Integer(), nullable=True),
    sa.Column('c1_blue', sa.Integer(), nullable=True),
    sa.Column('c2_red', sa.Integer(), nullable=True),
    sa.Column('c2_green', sa.Integer(), nullable=True),
    sa.Column('c2_blue', sa.Integer(), nullable=True),
    sa.Column('distinct', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data')
    # ### end Alembic commands ###
